### ISSUE TITLE
[Question]: Can you explain the derivation of the TTC?

### ISSUE THREAD

**Issue by bbrito** [davisbo/NHTTC#2]
Hi, 

Thanks for sharing your work! Can you explain how did you deduce the TTC equation in line https://github.com/davisbo/NHTTC/blob/2139ebcf7e4d9ac89a389c98a3d4302a6b9179a4/src/sgd/ttc_sgd_problem.cpp#L80

?

Best regards,
Bruno

**Comment by davisbo** [comment]
Hello--

Here's a write-up of the TTC solve.  Section 1 shows the basics of the quadratic solver, and Section 2 shows the modifications to the solve in Section 1 we do for numerical speed considerations.

Let me know if anything still doesn't make sense.
[TTC_solution.pdf](https://github.com/davisbo/NHTTC/files/5717611/TTC_solution.pdf)

--Bobby

**Comment by bbrito** [comment]
Dear Bobby,

Thank you so much for the quick and detailed reply. I'll check it later but I guess it should be fine ;)

Best regards,
Bruno
